#!/bin/bash
APP="$1"; IMAGE="dokku/$APP"

# Check for Procfile
ID=$(docker run -d $IMAGE test -f app/Procfile)
if [ $(docker wait $ID) -ne 0 ]; then
  echo "ABORT -- no Procfile in app"
  exit 0
fi

PM2SCRIPT=<<'EOF'
#!/bin/bash

export HOME=/app
export NODE=\$HOME/vendor/node/bin/node
export PM2=\$HOME/vendor/node/lib/node_modules/pm2
export PATH=\$PATH:\$HOME/vendor/node/bin:\$HOME/node_modules/.bin/
cd \$HOME
CMD=\$(head -n 1 Procfile | awk '{ print \$2 }')
PARAMS=\$(head -n 1 Procfile | awk '{ print \$3 \$4 \$5 \$6 }')
if [[ -f node_modules/.bin/\$CMD ]]; then 
	CMD="\$HOME/node_modules/.bin/\$CMD"
fi
\$NODE \$PM2 --no-daemon start $CMD $PARAMS
EOF

NOTIFICATION=<<'EOF'
#!/bin/bash

export HOME=/app
export NODE=\$HOME/vendor/node/bin/node
export PM2=\$HOME/vendor/node/lib/node_modules/pm2
export PATH=\$PATH:\$HOME/vendor/node/bin:\$HOME/node_modules/.bin/
cd \$HOME
\$NODE \$PM2 subscribe drmikecrowe@gmail.com
EOF

set -e


echo '-----> Injecting pm2 notification script'
CMD="/app/.pm2-notification"
id=$(echo "$NOTIFICATION" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > $CMD")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

echo '-----> Running pm2 notification script'
ID=$(docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null

echo '-----> Injecting pm2 startup script'
CMD="/app/.pm2-startup"
id=$(echo "$PM2SCRIPT" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > $CMD")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

echo '-----> Running pm2 startup script'
ID=$(docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
