#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

PLUGIN_DIR=$(dirname $0)
. "$PLUGIN_DIR/lib/helpers"

echo '-----> Injecting pm2 install script'
copy_to_container "$PLUGIN_DIR/lib/pm2-install" /app/.pm2-install y

echo '-----> Updating Procfile to use pm2'
copy_to_container "$PLUGIN_DIR/lib/pm2-update-procfile" /app/.pm2-update-procfile y
