#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

PLUGIN_DIR=$(dirname $0)
. "$PLUGIN_DIR/lib/helpers"

echo '-----> Installing pm2'
run_container_cmd "/app/.pm2-install"

echo '-----> Updating pm2 procfile'
run_container_cmd "/app/.pm2-update-procfile"
