#!/bin/bash

export HOME=/app
export NODE=$HOME/vendor/node/bin/node
export PM2=$HOME/vendor/node/lib/node_modules/pm2
cd $HOME
if [[ "`which node`" = "" ]]; then
	PATH=$PATH:/$HOME/vendor/node/bin:/$HOME/node_modules/.bin/
fi
if [[ ! -f $PM2 ]]; then
	npm install -g pm2
fi
